name: Send Naver News to Slack

on:
  schedule:
    - cron: "0 * * * *"      # 1시간 간격 (UTC 정각)
  workflow_dispatch:          # 수동 실행 버튼 허용

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4         # 비정상적으로 오래 걸리는 경우 자동 종료
    concurrency:               # 중복 실행 방지
      group: news-bot
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        run: python news_to_slack.py
